sudo: false
language: node_js
node_js:
- 6
- 8
notifications:
  email: false
  pushover:
    on_success: always
    on_failure: always
    api_key:
      secure: LICSK667BUJDL742wtggjKsj4MXMX6fSoqawpgdK/DBsM7EAOQ80abrS+ZWoSYaSgpv42ZWnzHPNs4dr2ZDv7/Sq74NMl75OWTFL/PqXdM7iZm7XGuS9hUMkTT/wKc8/WbHjMm0KcEPOXQ8H2RqpkIoOPB/xNHbH9TpCxqLm0EMCnmDKqZPiqnlz6HTKsIkWqSUXPXIqVS7Epfy0L0jEQJwH2ozvp5Vb0yqXtVmDncDMnpBx6Koo7rfi/TVR/6ge7w3Cg0/QJXBBZkXR0kHHnkCOeF4xEsUsr0FjxDbG1gVTRFr04+01kfHIeq12tTQj9IYygCdKcjvEf99dbARvx8nkSoEG1rskbUrFbEoRE8SUD7sGUwKBWDon5onLVEeuQTA4Snuq+amlcBBRNT5j0aYLkwYEJve//xpmqBO0VPZY3d1V3JvaP69F5kpkMeeW3hdb6PU4Kus+gXs/PF7IxOzcaZFQ6gZZUeZ2rrL5WuMtZZZ+rn3NzlnVuQoIg5QKfdVf5Jqpcr4vrBFEpZ5w8Ztbqixg4kxBnDLW9+ZFkx80Y0UebzYXpmOHDkVZcsr8Z/bVvoilmUjRNSH7i5U//12a7+c7oYkcJ9YyhYlenXWiVNnKhLpwyO7W5bZ7f/dSE0k/r9N+i4teCJ64UvAwtzrFdVnNh5/SVDpd6ztLmVY=
    users:
      secure: IH3CkWb2uYd1FcIexFaucSrMVSuNMwxAWUJXXYyD716NBz9LTM3YXkoyVRfW5sCxpBPYOApszl1JGW4g6qIX+ka1yHmRlDL0LRJbfdz+pykT05jblF8uqnMitjarSkEnfZNdLbs0IXGCIy3RdY95EpehY6aZcLGfdaxLSJ3x75jLTAxeTwpN1e4tj9hQOQbRNL/ylJNCOTOfOmfEZRA/VFkNxHrdHxGHvSzW/QQCJNMrkBm1u4o3kkWean7MrjycuutAKT/m+45G0epIN+JdlS2YjAu2ohKFfgw1zL4/N+RMUas/48fjh6iVqFXJ3xfMxlACdiSEYn/jzlaowce+fMM0yqZGqAPXosHzdZI46JCm3efG1ttsqOvOqADFrGbisy5CBKQ6C1ugO9QAiFGSK7yEY02qQ6DhIhkLP0rMqzf34dW8di5O31FbM9Pf+nk8GkcRZ3Ol/Ya/k1tJZ0j+745BtaKPCRrk1YH7FmHeW7zrP8uyEI0/vFYRpM2ALWzk99hRDMHA6VB6CD6RngjNzCOcZoWiGjILvcHYh/Cf8yiEx26OwVwtFJSO10zU0jup0aPuihL9SOtuJYW61LLydG+7A3ukVD6QzlJyLdjcrsQ7RbvGwAn07DLCy17NOvugF22Wered/pLPEdNeEbLfwD0Gz78MYRaE6lYRWqEIjAs=
    template: "%{repository_name} %{branch}#%{build_number}\n%{message}\nDetails: %{build_url}"